# syntax=docker/dockerfile:1
FROM ruby:3.2

ENV LANG=C.UTF-8 \
    TZ=Asia/Tokyo

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
        build-essential \
        libpq-dev \
        nodejs \
        git && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY Gemfile* .

RUN gem install bundler && bundle install

COPY . .

EXPOSE 4567

CMD ["bundle", "exec", "ruby", "app.rb", "-o", "0.0.0.0"]